# Effective Graph Paper
Code to generate "Table 1 - Canalization measures for variables in the Arabidopsis thaliana Model"

In [1]:
import pandas as pd
pd.options.display.float_format = '{:.2g}'.format
import cana
import networkx as nx
from cana.datasets.bio import THALIANA

In [2]:
T = THALIANA()

In [3]:
#SG = T.structural_graph()
EG = T.effective_graph(mode='input', bound='mean', threshold=-1)

In [4]:
bound = 'upper'
df = pd.DataFrame({
        'node':[n.name for n in T.nodes],
        'k':[n.k for n in T.nodes],
        'k_r':[n.input_redundancy(mode='node',bound=bound,norm=False) for n in T.nodes],
        'k_e':[n.effective_connectivity(mode='node',bound=bound,norm=False) for n in T.nodes],
        'k_r*':[n.input_redundancy(mode='node',bound=bound,norm=True) for n in T.nodes],
        'k_e*':[n.effective_connectivity(mode='node',bound=bound,norm=True) for n in T.nodes],
        'k^{out}':[v for n,v in EG.out_degree()],
        'k_e^{out}':[v for n,v in EG.out_degree(weight='weight')],
    }).set_index('node')
df = df[['k','k_r','k_e','k_r*','k_e*','k^{out}','k_e^{out}']]
df['k_e^{out} / k^{out}'] = df['k_e^{out}'] / df['k^{out}']
df.sort_values('k',ascending=False,inplace=True)
display(df)

      k  k_r  k_e  k_r*  k_e*  k^{out}  k_e^{out}  k_e^{out} / k^{out}
node
AG    9  6.9  2.1  0.77  0.23        5        1.9                 0.38
AP3   7  4.8  2.2  0.69  0.31        2        0.8                  0.4
PI    6  3.9  2.1  0.65  0.35        2       0.47                 0.24
AP1   4  2.4  1.6  0.61  0.39        6        1.4                 0.23
LFY   4  2.8  1.2  0.69  0.31        7        4.8                 0.69
TFL1  4  2.8  1.2  0.69  0.31        5        2.8                 0.57
WUS   3  1.5  1.5   0.5   0.5        2       0.91                 0.46
FUL   2 0.75  1.2  0.38  0.62        1          0                    0
UFO   1    0    1     0     1        2        1.6                 0.79
FT    1    0    1     0     1        1       0.24                 0.24
EMF1  1    0    1     0     1        3          2                 0.68
AP2   1    0    1     0     1        2       0.43                 0.22
SEP   1    0    1     0     1        4        0.9                 0.22
LUG   0    0    1     0     1        1        0.1                  0.1
CLF   0    0    1     0     1        1        0.1                  0.1

In [5]:
# to Latex
print(df.to_latex(escape=False))

\begin{tabular}{lrrrrrrrr}
\toprule
{} &  k &  k_r &  k_e &  k_r* &  k_e* &  k^{out} &  k_e^{out} &  k_e^{out} / k^{out} \\
node &    &      &      &       &       &          &            &                      \\
\midrule
AG   &  9 &  6.9 &  2.1 &  0.77 &  0.23 &        5 &        1.9 &                 0.38 \\
AP3  &  7 &  4.8 &  2.2 &  0.69 &  0.31 &        2 &        0.8 &                  0.4 \\
PI   &  6 &  3.9 &  2.1 &  0.65 &  0.35 &        2 &       0.47 &                 0.24 \\
AP1  &  4 &  2.4 &  1.6 &  0.61 &  0.39 &        6 &        1.4 &                 0.23 \\
LFY  &  4 &  2.8 &  1.2 &  0.69 &  0.31 &        7 &        4.8 &                 0.69 \\
TFL1 &  4 &  2.8 &  1.2 &  0.69 &  0.31 &        5 &        2.8 &                 0.57 \\
WUS  &  3 &  1.5 &  1.5 &   0.5 &   0.5 &        2 &       0.91 &                 0.46 \\
FUL  &  2 & 0.75 &  1.2 &  0.38 &  0.62 &        1 &          0 &                    0 \\
UFO  &  1 &    0 &    1 &     0 &     1 &        2 &        1.6 &                 0.79 \\
FT   &  1 &    0 &    1 &     0 &     1 &        1 &       0.24 &                 0.24 \\
EMF1 &  1 &    0 &    1 &     0 &     1 &        3 &          2 &                 0.68 \\
AP2  &  1 &    0 &    1 &     0 &     1 &        2 &       0.43 &                 0.22 \\
SEP  &  1 &    0 &    1 &     0 &     1 &        4 &        0.9 &                 0.22 \\
LUG  &  0 &    0 &    1 &     0 &     1 &        1 &        0.1 &                  0.1 \\
CLF  &  0 &    0 &    1 &     0 &     1 &        1 &        0.1 &                  0.1 \\
\bottomrule
\end{tabular}